### ISSUE TITLE
Python was not found

### ISSUE THREAD

**Issue by syvshc** [tndrle/PyLuaTeX#1]
Hello! I'm testing the first example in the doc:
```latex
\documentclass{article}
\usepackage{pyluatex}
\begin{python}
import math
import random
random.seed(0)
greeting = ’Hello PyLuaTeX!’
\end{python}
\newcommand{\randint}[2]{\py{random.randint(#1, #2)}}
\begin{document}
\py{greeting}
$\sqrt{371} = \py{math.sqrt(371)}$
\randint{2}{5}
\end{document}
```
And I met an error:
```
(c:/texlive/2021/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty))Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```
but I'm sure I have installed python with anaconda. 

![image](https://user-images.githubusercontent.com/38098591/126062401-c118e5be-13bf-4a06-a46e-358ea02bf93d.png)

Does it mean that I have to install python from Microsoft Store, or I have to specify the executable manually?

**Comment by syvshc** [comment]
Oh! I use `\usepackage[executable=python]{pyluatex}` and it works. I think it is because in windows `python3` have to be called with `python`.... Any way it's fine :)

**Comment by tndrle** [comment]
Hi, thanks for reporting. I have to admit that I haven't spent too much time on Windows compatibility, yet. In my setup, I have installed Python from the Microsoft Store and I can call it with `python3`. Knowing that this is not the case for Anaconda is very helpful, thank you.
