### ISSUE TITLE
Can one access args given to luatex within pyluatex?

### ISSUE THREAD

**Issue by kiryph** [tndrle/PyLuaTeX#13]
Based on this answer https://tex.stackexchange.com/a/18813/8917 I am wondering whether it would be possible to provide, e.g. a special python package to access the luatex table args?

My current approach is:

```
$ lualatex --output-format=pdf --shell-escape --jobname='[12]_p6mm(17)' "\documentclass{standalone}\usepackage{pyluatex}\pyc{dim=2;group=17;index=12}\input{myfile}”
```

which is a bit lengthy on the command line. I would prefer a shorter version:
```
$ lualatex --output-format=pdf --shell-escape myfile.tex 2 17 12
```

**Comment by tndrle** [comment]
You can use the following to pass LuaTeX's `arg` to Python:

```
\documentclass{article}
\usepackage{pyluatex}

\pyc{args = '\directlua{tex.sprint(table.concat(arg, ";"))}'}
\pyc{dim, group, index = args.split(';')[3:]}

\begin{document}
\py{(dim, group, index)}
\end{document}
```

Is that what you're after?

**Comment by kiryph** [comment]
@tndrle Yes, that is it. Thank you.
