### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by jowe19** [tndrle/PyLuaTeX#14]
Hi, 
since today, the following code gives an error. How can I fix it ? I have checked the indentation but without any success. 

Regards, 
Jonathan

```
\documentclass{article}

\usepackage{pyluatex}

\begin{document}

\begin{python}
def deux_maxi(L):
	"""
	retourne les deux plus grands éléments, où seulement le plus grand si L est de taille 1
	"""
	if len(L) == 1:
	    return L[0]
    else:
    	maxi = maximum(L)
    	while maxi in L:
    		L.remove(maxi)
    	if len(sec_maxi) == 0:
    		return maxi
    	else:
    		return maxi, maximum(L)
\end{python}

\end{document}
```
[Untitled.log](https://github.com/tndrle/PyLuaTeX/files/9749135/Untitled.log)

**Comment by tndrle** [comment]
Hi,
you are mixing tabs and spaces for indentation. I guess that's the problem.
It's not specific to PyLuaTeX, it doens't work in pure Python either.
I suggest you use either tabs or spaces but not both.
