### ISSUE TITLE
Why new environment name `python` instead of `pycode` used in pythontex & pythonimmediate?

### ISSUE THREAD

**Issue by kiryph** [tndrle/PyLuaTeX#17]
Pythontex ([first release on CTAN 2013-04-29](https://ctan.org/ctan-ann/pkg/pythontex)) uses as environment names following:

- `\begin{pycode}`
- `\begin{pycodeq}`

The new package [pythonimmediate](https://www.ctan.org/pkg/pythonimmediate) picked the names from pythontex to become a drop-in replacement.

The [treesitter grammar for latex](https://github.com/latex-lsp/tree-sitter-latex) has added `pycode` to enable language injection of python in latex files:

- https://github.com/latex-lsp/tree-sitter-latex/blob/master/src/grammar.json#L2774-L2791

which Im interested right now.

I am torn between asking tree sitter grammar to add `python` as well. But on the other hand I think pyluatex could be a drop-in replacement for pythontex as well which would be a reason to share the same environment names.

Could pyluatex add the environment names `pycode` and `pycodeq`  as aliases (maybe only if not defined allowing user to use both packages which, however, I would not recommend)?

**Comment by tndrle** [comment]
You can define aliases yourself, e.g.
```latex
\documentclass{article}

\usepackage{pyluatex}

\newenvironment{pycode}{\PyLTVerbatimEnv\begin{python}}{\end{python}}

\begin{document}
\begin{pycode}
print("text")
\end{pycode}
\end{document}
```

Would that be a solution for you?

**Comment by kiryph** [comment]
I would argue modifying the document to adjust for the editor (or here tree-sitter grammar) one uses is not desirable.

**Comment by tndrle** [comment]
In the long run, it is not desirable, I agree. I wasn't sure about your use case.

That said, it doesn't seem reasonable to mimic the interface of PythonTeX here. PythonTeX and PyLuaTeX are similar, yes, but there will also always be differences. I'm afraid adding aliases now will lead to further requests of that kind in the future.

The preferred approach would be what you suggest:
> [...] asking tree sitter grammar to add `python` as well.

**Comment by kiryph** [comment]
> I'm afraid adding aliases now will lead to further requests of that kind in the future.

I am not sure whether there will be every year a new "python" package on CTAN.

But I see your point.

I will try now`pythonimmediate` if it fulfils my needs and I can change once the environment names to the ones the tree sitter grammar recognises as python code injection.

I plan to ask tree sitter to support the environment names from pyluatex as well. I will see how this goes.
