### ISSUE TITLE
Missing folder "example" in TeX Live

### ISSUE THREAD

**Issue by quark67** [tndrle/PyLuaTeX#9]
On the documentation (path: `/usr/local/texlive/2021/texmf-dist/doc/lualatex/pyluatex/pyluatex.pdf`) we read: 
_**1.1 Further Examples**
The folder `example` contains additional example documents:_

There isn't an "example" folder after installation of the package by TeX Live.

Furthermore: there isn't an "example" folder on CTAN (https://ctan.org/tex-archive/macros/luatex/latex/pyluatex).

Can the "example" folder be added to CTAN and TeX Live? I know that the example folder can be found here, in this GitHub repository, but majority of end users probably prefer to find the complete documentation (with examples) on their local LaTeX installation.

**Comment by tndrle** [comment]
Fixed in v0.4.3
